action_id: trunk-share-with-everyone
date: 2024-02-24 22:20:54
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1708813254
full_timestamp:
  nanos: 712012000
  seconds: 1708813254
trunk_version: 1.18.1
